
data: 
  customersData: /Users/mpatel/Documents/GitHub/lvs_DB/customers.json
  invoicesData: /Users/mpatel/Documents/GitHub/lvs_DB/invoices.json
  productsData: /Users/mpatel/Documents/GitHub/lvs_DB/products.json
  inventoryData: /Users/mpatel/Documents/GitHub/lvs_DB/inventory.json

dataJul:
  customersData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/customers_july.json
  invoicesData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/invoices_july.json
  productsData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/products_july.json
  inventoryData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/inventory_july.json

dataSep:
  customersData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/customers_september.json
  invoicesData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/invoices_september.json
  productsData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/products_september.json
  inventoryData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/inventory_september.json

dataOct:
  customersData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/customers_october.json
  invoicesData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/invoices_october.json
  productsData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/products_october.json
  inventoryData: /Users/mpatel/Documents/GitHub/lvs_DB/2025/inventory_october.json


dataTest:
  customersData: /Users/mpatel/Documents/GitHub/lvs_DB/test/customers_test.json
  invoicesData: /Users/mpatel/Documents/GitHub/lvs_DB/test/invoices_test.json
  productsData: /Users/mpatel/Documents/GitHub/lvs_DB/test/products_test.json
  inventoryData: /Users/mpatel/Documents/GitHub/lvs_DB/test/inventory_test.json