apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btree-claim 
  namespace: default
spec:
  accessModes:
    - ReadWrite
  resources:
    requests: 
      storage: 10Gi
  storageClassName: default

---
apiVersion: v1
kind: Service
metadata:
  name: p4d-svc
  labels:
    app: p4d
  namespace: default
spec:
  ports:
  - port: 4232
    name: p4d-port
  clusterIP: None
  selector:
    app: p4d
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: p4d-state
  namespace: default
spec:
  selector:
    matchLabels:
      app: p4d # has to match .spec.template.metadata.labels
      server: master
  serviceName: "p4d-sa"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: p4d # has to match .spec.selector.matchLabels
        server: master
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: p4d-ctr
        image: immnan/p4d:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4232
          name: p4d-port
        volumeMounts:
        - name: btree
          mountPath: /var/p4d-root/
  volumeClaimTemplates:
  - metadata:
      name: btree
    persistentVolumeClaimSpec:
      claimName: btree-claim
